# Generated by Django 5.1.6 on 2025-02-28 17:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("code_description", models.TextField()),
                ("mfu_50th", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mfu_75th", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mfu_90th", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pfr_50th", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pfr_75th", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pfr_90th", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mfr_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pfr_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Evaluee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("date_of_injury", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "life_expectancy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeographicFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zip", models.CharField(db_index=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state_id", models.CharField(max_length=2)),
                ("state_name", models.CharField(max_length=100)),
                ("county_fips", models.CharField(max_length=10)),
                ("county_name", models.CharField(max_length=100)),
                ("mfr_code", models.CharField(max_length=10)),
                ("pfr_code", models.CharField(max_length=10)),
                (
                    "gaf_lookup",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "mfr_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pfr_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="LifeCarePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("date_of_injury", models.DateField(blank=True, null=True)),
                ("race", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("street_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("county_apc", models.CharField(blank=True, max_length=100)),
                ("county_drg", models.CharField(blank=True, max_length=100)),
                ("age_at_injury", models.IntegerField(blank=True, null=True)),
                (
                    "statistical_lifespan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("use_age_increments", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_care_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarePlanEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("physicianEvaluation", "Physician Evaluation"),
                            ("physicianFollowUp", "Physician Follow-up"),
                            ("therapyEvaluation", "Therapy Evaluation"),
                            ("therapyFollowUp", "Therapy Follow-up"),
                            ("medication", "Medication"),
                            ("surgical", "Surgical"),
                            ("dme", "DME"),
                            ("supplies", "Supplies"),
                            ("homeCare", "Home Care"),
                            ("homeModification", "Home Modification"),
                            ("transportation", "Transportation"),
                            ("interventional", "Interventional"),
                            ("diagnostics", "Diagnostics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
                ("cpt_code", models.CharField(blank=True, max_length=50)),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("annual_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lifetime_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_age", models.IntegerField(blank=True, null=True)),
                ("end_age", models.IntegerField(blank=True, null=True)),
                ("is_one_time", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("use_age_increments", models.BooleanField(default=False)),
                ("age_increments", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="lifecare.lifecareplan",
                    ),
                ),
            ],
        ),
    ]
